const DashboardStyle = {
  container: {
    padding: "24px",
    maxWidth: "1400px",
    margin: "0 auto",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "32px",
    flexWrap: "wrap",
    gap: "16px",
  },
  projectTitle: {
    fontSize: "36px",
    fontWeight: 700,
    color: "#0F3E2D",
    margin: 0,
    letterSpacing: "-0.5px",
  },
  editProjectBtn: {
    padding: "12px 24px",
    backgroundColor: "#fff",
    color: "#333",
    border: "1px solid #d1d5db",
    borderRadius: "10px",
    fontSize: "15px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxShadow: "0 2px 6px rgba(0,0,0,0.08)",
  },
  statsContainer: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "24px",
    marginBottom: "40px",
  },
  statCard: {
    backgroundColor: "#fff",
    padding: "28px",
    borderRadius: "16px",
    boxShadow: "0 4px 12px rgba(0,0,0,0.08)",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    border: "1px solid rgba(15, 62, 45, 0.06)",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
    alignItems: "center",
    textAlign: "center",
  },
  statLabel: {
    fontSize: "13px",
    fontWeight: 700,
    color: "#555",
    textTransform: "uppercase",
    letterSpacing: "1px",
  },
  statValue: {
    fontSize: "32px",
    fontWeight: 700,
    color: "#0F3E2D",
    lineHeight: 1.2,
    whiteSpace: "nowrap",
  },
  statValueSmall: {
    fontSize: "18px",
    fontWeight: 700,
    color: "#0F3E2D",
    lineHeight: 1.4,
  },
  statSubtext: {
    fontSize: "15px",
    fontWeight: 600,
    color: "#6c6c6cff",
    marginTop: "4px",
  },
  dueWarning: {
    fontSize: "13px",
    color: "#e11d48",
    fontWeight: 700,
    marginTop: "4px",
  },
  progressBarContainer: {
    backgroundColor: "#e8eef1",
    borderRadius: "8px",
    height: "10px",
    overflow: "hidden",
    width: "100%",
    marginTop: "8px",
  },
  progressBar: {
    backgroundColor: "#1e3a8a",
    height: "100%",
    borderRadius: "8px",
    transition: "width 0.5s ease",
    minWidth: "2px",
  },
  quickActions: {
    marginTop: "40px",
  },
  sectionTitle: {
    fontSize: "22px",
    fontWeight: 700,
    color: "#0F3E2D",
    marginBottom: "20px",
    letterSpacing: "-0.3px",
  },
  actionCardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: "20px",
  },
  actionCard: {
    backgroundColor: "#fff",
    padding: "28px",
    borderRadius: "16px",
    border: "1px solid rgba(15, 62, 45, 0.06)",
    cursor: "pointer",
    transition: "all 0.2s ease",
    boxShadow: "0 4px 12px rgba(0,0,0,0.06)",
  },
  actionCardTitle: {
    fontSize: "18px",
    fontWeight: 700,
    color: "#0F3E2D",
    marginBottom: "8px",
    letterSpacing: "-0.2px",
  },
  actionCardDesc: {
    fontSize: "14px",
    color: "#666",
    lineHeight: 1.5,
  },
};

export default DashboardStyle;
