const HomePageStyle = {
  page: {
    position: "fixed",
    inset: 0,
    backgroundColor: "#DDF9EA",
    boxSizing: "border-box",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    overflow: "auto",
  },
  inner: {
    width: "100%",
    maxWidth: 1000,
    marginTop: 40,
    padding: 24,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 24,
    position: "relative",
  },
  heading: {
    fontSize: 44,
    fontWeight: 800,
    margin: 0,
    color: "#0F3E2D",
    textAlign: "center",
    fontFamily: "Inter, Arial, sans-serif",
  },
  subtitle: {
    color: "#2e7d32",
    fontSize: 18,
    marginTop: -8,
    textAlign: "center",
  },
  alertsCard: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 12,
    border: "1px solid #a3b7acff",
    boxShadow: "0 2px 0 rgba(0,0,0,0.06)",
    padding: "16px 18px 10px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  alertsHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  alertsTitle: {
    fontSize: 20,
    fontWeight: 700,
    color: "#0F3E2D",
  },
  alertsSubtitle: {
    fontSize: 14,
    color: "#1f6935",
    marginTop: 4,
  },
  alertsBadge: {
    padding: "8px 12px",
    borderRadius: 999,
    fontWeight: 700,
    fontSize: 13,
    border: "1px solid #c7d2fe",
  },
  alertsList: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  alertItem: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 10,
    backgroundColor: "#f8fafc",
    border: "1px solid #e2e8f0",
  },
  alertIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 800,
    fontSize: 18,
  },
  alertContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  alertTask: {
    fontSize: 16,
    fontWeight: 700,
    color: "#0F3E2D",
  },
  alertMeta: {
    fontSize: 13,
    color: "#1f2937",
  },
  alertDue: {
    textAlign: "right",
    fontWeight: 700,
    fontSize: 14,
  },
  alertDate: {
    fontSize: 12,
    color: "#4b5563",
  },
  alertsEmpty: {
    width: "100%",
    backgroundColor: "#f8fafc",
    borderRadius: 10,
    border: "1px dashed #a3b7acff",
    padding: "12px 14px",
    color: "#1f2937",
    fontSize: 14,
    boxSizing: "border-box",
  },
  alertGroup: {
    borderTop: "1px solid #e5e7eb",
    paddingTop: 10,
  },
  alertGroupHeader: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 12px",
    borderRadius: 10,
    border: "1px solid #e2e8f0",
    cursor: "pointer",
    transition: "background-color 0.2s ease",
  },
  alertGroupLeft: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  alertGroupTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: "#0F3E2D",
  },
  alertGroupCount: {
    fontSize: 13,
    color: "#1f2937",
    padding: "4px 8px",
    backgroundColor: "#e5e7eb",
    borderRadius: 999,
    fontWeight: 600,
  },
  alertGroupIcon: {
    fontSize: 14,
    color: "#1f2937",
  },
  expandBtn: {
    padding: "8px",
    backgroundColor: "#f8fafc",
    border: "1px solid #e2e8f0",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: 16,
    lineHeight: 1,
    transition: "background-color 0.2s ease",
  },
  cardExpand: {
    marginTop: -4,
    padding: "8px 12px 10px 12px",
    backgroundColor: "#f9fafb",
    border: "1px solid #e2e8f0",
    borderRadius: 10,
    boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    width: "100%",
    boxSizing: "border-box",
  },
  list: {
    width: "100%",
    marginTop: 8,
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },
  card: {
    background: "#fff",
    borderRadius: 12,
    padding: "16px 20px",
    border: "1px solid #a3b7acff",
    boxShadow: "0 2px 0 rgba(0,0,0,0.06)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    cursor: "pointer",
  },
  cardLeft: {
    display: "flex",
    alignItems: "center",
    gap: 16,
  },
  badge: {
    width: 40,
    height: 36,
    borderRadius: 8,
    background: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: 24,
  },
  cardContent: {
    display: "flex",
    flexDirection: "column",
  },
  cardTitle: {
    fontSize: 22,
    fontWeight: 600,
  },
  cardMeta: {
    display: "flex",
    gap: 24,
    color: "#333",
    alignItems: "center",
  },
  metaText: {
    fontStyle: "italic",
  },
  newProjectBtn: {
    marginLeft: 0,
    padding: "12px 24px",
    backgroundColor: "#fff",
    color: "#333",
    border: "1px solid #a3b7acff",
    boxShadow: "0 2px 0 rgba(0,0,0,0.06)",
    borderRadius: 8,
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    alignSelf: "flex-start",
  },
  logoutBtn: {
    position: "fixed",
    top: 12,
    left: 8,
    width: 50,
    height: 50,
    backgroundColor: "#DDF9EA",
    border: 0,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 28,
    color: "#0F3E2D",
    fontWeight: "bold",
    zIndex: 100,
  },
  emptyState: {
    width: "100%",
    maxWidth: 600,
    marginTop: 16,
    padding: "32px 24px",
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    borderRadius: 12,
    border: "2px dashed rgba(15, 62, 45, 0.2)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 16,
    textAlign: "center",
  },
  emptyStateIcon: {
    fontSize: 56,
    opacity: 0.3,
  },
  emptyStateTitle: {
    fontSize: 26,
    fontWeight: 700,
    color: "#0F3E2D",
    margin: 0,
  },
  emptyStateDescription: {
    fontSize: 15,
    color: "#2e7d32",
    lineHeight: 1.5,
    maxWidth: 400,
  },
  emptyStateCTA: {
    marginTop: 8,
    padding: "12px 24px",
    backgroundColor: "#1e3a8a",
    color: "white",
    border: "none",
    borderRadius: 10,
    fontSize: 18,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 4px 12px rgba(30, 58, 138, 0.3)",
    transition: "all 0.2s ease",
  },
};

export default HomePageStyle;
