const HomePageStyle = {
  page: {
    position: "fixed",
    inset: 0,
    backgroundColor: "#DDF9EA",
    boxSizing: "border-box",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    overflow: "auto",
  },
  inner: {
    width: "100%",
    maxWidth: 1000,
    marginTop: 40,
    padding: 24,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 24,
    position: "relative",
  },
  heading: {
    fontSize: 44,
    fontWeight: 800,
    margin: 0,
    color: "#0F3E2D",
    textAlign: "center",
    fontFamily: "Inter, Arial, sans-serif",
  },
  subtitle: {
    color: "#2e7d32",
    fontSize: 18,
    marginTop: -8,
    textAlign: "center",
  },
  list: {
    width: "100%",
    marginTop: 8,
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },
  card: {
    background: "#fff",
    borderRadius: 12,
    padding: "16px 20px",
    border: "1px solid #a3b7acff",
    boxShadow: "0 2px 0 rgba(0,0,0,0.06)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    cursor: "pointer",
  },
  cardLeft: {
    display: "flex",
    alignItems: "center",
    gap: 16,
  },
  badge: {
    width: 40,
    height: 36,
    borderRadius: 8,
    background: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: 24,
  },
  cardContent: {
    display: "flex",
    flexDirection: "column",
  },
  cardTitle: {
    fontSize: 22,
    fontWeight: 600,
  },
  cardMeta: {
    display: "flex",
    gap: 24,
    color: "#333",
    alignItems: "center",
  },
  metaText: {
    fontStyle: "italic",
  },
  newProjectBtn: {
    marginLeft: 20,
    padding: "12px 24px",
    backgroundColor: "#fff",
    color: "#333",
    border: "1px solid #a3b7acff",
    boxShadow: "0 2px 0 rgba(0,0,0,0.06)",
    borderRadius: 8,
    fontSize: 16,
    fontWeight: 600,
    cursor: "pointer",
    alignSelf: "flex-start",
  },
  logoutBtn: {
    position: "fixed",
    top: 12,
    left: 8,
    width: 50,
    height: 50,
    backgroundColor: "#DDF9EA",
    border: 0,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 28,
    color: "#0F3E2D",
    fontWeight: "bold",
    zIndex: 100,
  },
};

export default HomePageStyle;
