const MessageThreadStyle = {
    container: {
        backgroundColor: "#f3f4f6",
        display: "flex",
        flexDirection: "column",
        height: "100vh",
        overflow: "hidden",
    },
    layout: {
        display: "flex",
        flex: 1,
        backgroundColor: "#ffffff",
        overflow: "hidden",
    },
    main: {
        flex: 1,
        display: "flex",
        flexDirection: "column",
        overflow: "hidden",
        minHeight: 0,
        backgroundColor: "#ffffff",
    },
    header: {
        padding: "1rem 1.5rem",
        flexShrink: 0,
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: "1rem",
        width: "100%",
        backgroundColor: "#ffffff",
        borderBottom: "1px solid #e5e7eb",
        boxShadow: "0 1px 2px rgba(0, 0, 0, 0.05)",
        height: '73px',
        boxSizing: 'border-box',
    },
    // RESPONSIVE: Mobile header (smaller screens)
    '@media (max-width: 768px)': {
        header: {
            padding: "0.75rem 1rem",
            height: 'auto',
            minHeight: '60px',
        },
    },
    chatTitle: {
        margin: 0,
        fontSize: "1.125rem",
        fontWeight: "600",
        color: "#1f2937",
        lineHeight: "1.5",
    },
    // RESPONSIVE: Smaller title on mobile
    chatTitleMobile: {
        fontSize: "1rem",
    },
    channelBadge: {
        display: "inline-flex",
        alignItems: "center",
        backgroundColor: "#dbeafe",
        color: "#1e40af",
        padding: "3px 8px",
        borderRadius: "4px",
        fontSize: "0.8125rem",
        fontWeight: "600",
        marginLeft: "8px",
        lineHeight: "1.2",
    },
    chatWindow: {
        flex: 1,
        overflowY: "auto",
        display: "flex",
        flexDirection: "column",
        padding: "1.5rem",
        backgroundColor: "#f9fafb",
        minHeight: 0,
    },
    // RESPONSIVE: Less padding on mobile
    chatWindowMobile: {
        padding: "1rem",
    },
    messageBubble: {
        backgroundColor: "#e5e7eb",
        padding: "0.75rem 1rem",
        borderRadius: "12px",
        maxWidth: "60%",
    },
    // RESPONSIVE: Wider bubbles on mobile
    messageBubbleMobile: {
        maxWidth: "85%",
    },
    messageGroup: {
        display: 'flex',
        flexDirection: 'column',
        marginBottom: '1.5rem',
        width: '100%',
    },
    messageAuthor: {
        fontSize: "0.8125rem",
        fontWeight: "600",
        marginBottom: "4px",
        lineHeight: "1.2",
    },
    messageContent: {
        fontSize: "0.9375rem",
        lineHeight: "1.5",
        wordBreak: "break-word",
    },
    messageTime: {
        fontSize: "0.6875rem",
        opacity: 0.7,
        marginTop: "4px",
        lineHeight: "1.2",
    },
    dateSeparator: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        margin: '1.5rem 0',
        width: '100%',
    },
    dateSeparatorLine: {
        flex: 1,
        height: '1px',
        backgroundColor: '#e5e7eb',
    },
    dateSeparatorText: {
        padding: '0 1rem',
        fontSize: '0.75rem',
        fontWeight: '600',
        color: '#6b7280',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
    },
    inputArea: {
        display: "flex",
        gap: "0.75rem",
        flexShrink: 0,
        position: "relative",
        padding: "1rem 1.5rem",
        backgroundColor: "#ffffff",
        borderTop: "1px solid #e5e7eb",
    },
    // RESPONSIVE: Stack input on small screens if needed
    inputAreaMobile: {
        padding: "0.75rem 1rem",
    },
    input: {
        flex: 1,
        padding: "0.75rem",
        borderRadius: "8px",
        border: "1px solid #d1d5db",
        backgroundColor: "#ffffff",
        fontSize: "0.9375rem",
        color: "#374151",
        transition: "border-color 0.2s",
        fontFamily: "inherit",
        lineHeight: "1.5",
    },
    sendButton: {
        padding: "0.75rem 1.5rem",
        backgroundColor: "#1e3a8a",
        color: "#fff",
        border: "none",
        borderRadius: "8px",
        cursor: "pointer",
        fontWeight: "600",
        fontSize: "0.875rem",
        transition: "background-color 0.2s",
        lineHeight: "1.2",
    },
    // RESPONSIVE: Smaller button on mobile
    sendButtonMobile: {
        padding: "0.75rem 1rem",
        fontSize: "0.8125rem",
    },
    memberCount: {
        fontSize: "0.8125rem",
        color: "#6b7280",
        marginTop: "4px",
        lineHeight: "1.5",
    },
    memberLink: {
        color: "#1e3a8a",
        cursor: "pointer",
        textDecoration: "underline",
        marginLeft: "4px",
        fontWeight: "500",
    },
    memberDropdown: {
        position: "absolute",
        top: "100%",
        left: 0,
        marginTop: "8px",
        backgroundColor: "white",
        border: "1px solid #e5e7eb",
        borderRadius: "8px",
        boxShadow: "0 4px 12px rgba(0, 0, 0, 0.1)",
        padding: "12px",
        minWidth: "200px",
        maxWidth: "300px",
        zIndex: 1000,
    },
    memberDropdownHeader: {
        fontWeight: "600",
        marginBottom: "8px",
        color: "#1f2937",
        fontSize: "0.8125rem",
        borderBottom: "1px solid #e5e7eb",
        paddingBottom: "8px",
        lineHeight: "1.2",
    },
    memberItem: {
        padding: "6px 0",
        color: "#374151",
        fontSize: "0.875rem",
        lineHeight: "1.5",
    },
    emptyState: {
        textAlign: "center",
        color: "#9ca3af",
        padding: "60px 40px",
        fontStyle: "italic",
        fontSize: "0.875rem",
        lineHeight: "1.5",
    },
    characterCount: {
        position: "absolute",
        bottom: "12px",
        right: "12px",
        fontSize: "0.6875rem",
        pointerEvents: "none",
        lineHeight: "1.2",
    },
};

export default MessageThreadStyle;
