const MessageThreadStyle = {
  container: {
    backgroundColor: "#f3f4f6",
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    overflow: "hidden",
  },
  layout: {
    display: "flex",
    flex: 1,
    backgroundColor: "#ddf9ea",
    overflow: "hidden",
  },
  main: {
    flex: 1,
    padding: "2rem",
    backgroundColor: "#ddf9ea",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    minHeight: 0,
  },
  header: {
    marginBottom: "1rem",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "1rem",
    width: "100%",
  },
  chatTitle: {
    margin: 0,
    fontSize: "1.5rem",
    fontWeight: "600",
  },
  chatWindow: {
    flex: 1,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    padding: "1rem",
    backgroundColor: "#fff",
    borderRadius: "8px",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.05)",
    minHeight: 0,
  },
  messageBubble: {
    backgroundColor: "#e5e7eb",
    padding: "1rem",
    borderRadius: "8px",
    maxWidth: "60%",
  },
  inputArea: {
    display: "flex",
    marginTop: "1rem",
    gap: "1rem",
    flexShrink: 0,
    position: "relative",
  },
  input: {
    flex: 1,
    padding: "0.75rem",
    borderRadius: "8px",
    border: "1px solid #d1d5db",
  },
  sendButton: {
    padding: "0.75rem 1.5rem",
    backgroundColor: "#1e3a8a",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
  },
};

export default MessageThreadStyle;