const MyTasksStyle = {
  container: {
    backgroundColor: "white",
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    overflow: "hidden",
  },
  layout: {
    display: "flex",
    flex: 1,
    backgroundColor: "#ddf9ea",
    overflow: "hidden",
  },
  main: {
    flex: 1,
    padding: "0.75rem 1rem 0.75rem 0.75rem",
    backgroundColor: "#DDF9EA",
    overflowX: "auto",
    overflowY: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "1rem",
    marginTop: "-1rem",
  },
  headerShift: {
    marginTop: "0rem",
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  swimlaneContainer: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: "0.5rem",
    alignItems: "stretch",
    width: "100%",
    flex: 1,
    minHeight: 0,
    marginTop: "0.5rem",
  },
  swimlane: {
    backgroundColor: "white",
    padding: "0.25rem 0.6rem 0.6rem 0.6rem",
    borderRadius: "8px",
    minWidth: "0",
    maxWidth: "100%",
    boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
    display: "flex",
    flexDirection: "column",
    height: "94%",
    overflow: "hidden",
    border: "1px solid #e5e5e5",
  },  
  swimlaneTitle: {
    fontSize: "0.95rem",
    fontWeight: "bold",
    marginBottom: "0.5rem",
    flexShrink: 0,
  },
  swimlaneContent: {
    flex: 1,
    overflowY: "auto",
    overflowX: "hidden",
    paddingRight: "0.25rem",
  },
  taskCard: {
    backgroundColor: "#ffffff",
    padding: "0.5rem",
    borderRadius: "8px",
    marginBottom: "0.75rem",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    border: "1px solid #e0e0e0",
  },  
  taskTitle: {
    fontWeight: "600",
    marginBottom: "0.25rem",
    fontSize: "0.95rem",
  },
  taskDescription: {
    fontSize: "0.85rem",
    marginBottom: "0.25rem",
    color: "#666",
  },
  taskDueDate: {
    fontSize: "0.75rem",
    color: "#888",
  },
};

export default MyTasksStyle;
