const ProfileStyle = {
  container: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
  },
  layout: {
    display: "flex",
    flex: 1,
    backgroundColor: "#f3f4f6",
  },
  main: {
    flex: 1,
    padding: "2rem",
    backgroundColor: "#ddf9ea",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    paddingTop: "3rem",
  },
  profilePanel: {
    backgroundColor: "#ffffff",
    padding: "0",
    borderRadius: "20px",
    boxShadow: "0 10px 40px rgba(0,0,0,0.1)",
    width: "100%",
    maxWidth: 800,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  profileHeader: {
    background: "linear-gradient(135deg, #2563EB 0%, #1e40af 100%)",
    padding: "3rem 2rem",
    display: "flex",
    alignItems: "center",
    gap: "2rem",
    color: "#ffffff",
  },
  profileHeaderText: {
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    paddingLeft: "1rem",
  },
  profileName: {
    fontSize: "2rem",
    fontWeight: 700,
    margin: 0,
    color: "#ffffff",
  },
  profileEmail: {
    fontSize: "1rem",
    margin: 0,
    opacity: 0.9,
    color: "#e0e7ff",
  },
  divider: {
    height: "1px",
    backgroundColor: "#e5e7eb",
    margin: "0",
  },
  infoSection: {
    padding: "2rem",
  },
  sectionTitle: {
    fontSize: "1.25rem",
    fontWeight: 600,
    color: "#1f2937",
    marginBottom: "1.5rem",
    marginTop: 0,
  },
  infoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "1.5rem",
  },
  infoCard: {
    backgroundColor: "#f9fafb",
    padding: "1.25rem",
    borderRadius: "12px",
    display: "flex",
    flexDirection: "column",
    gap: "0.5rem",
    border: "1px solid #e5e7eb",
    transition: "all 0.2s ease",
    cursor: "default",
  },
  infoLabel: {
    fontSize: "0.875rem",
    fontWeight: 500,
    color: "#6b7280",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  infoValue: {
    fontSize: "1.25rem",
    fontWeight: 700,
    color: "#1f2937",
  },
  actionButtons: {
    display: "flex",
    justifyContent: "flex-end",
    padding: "1.5rem 2rem 2rem 2rem",
    gap: "1rem",
    backgroundColor: "#f9fafb",
  },
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  popup: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: "2rem",
    textAlign: "center",
    width: "90%",
    maxWidth: 300,
    boxShadow: "0 10px 40px rgba(0,0,0,0.2)",
  },
  popupText: {
    fontSize: 18,
    fontWeight: 600,
    color: "#1f2937",
  },
};

export default ProfileStyle;
