const storeStyles = {
  container: {
    backgroundColor: "#f3f4f6",
    minHeight: "100vh",
  },
  layout: {
    display: "flex",
    backgroundColor: "#ddf9ea",
  },
  main: {
    flex: 1,
    padding: 24,
    paddingTop: 40,
    backgroundColor: "#ddf9ea",
    position: "relative",
  },
  profileIcon: {
    position: "absolute",
    top: 20,
    right: 40,
    zIndex: 10,
  },
  content: {
    maxWidth: 1400,
    margin: "0 auto",
    display: "flex",
    gap: 16,
    alignItems: "flex-start",
    flexWrap: "wrap",
    paddingTop: 80,
  },
  left: {
    flex: "1 1 500px",
    minWidth: "300px",
    backgroundColor: "#1E88E5",
    borderRadius: 8,
    padding: "0px 16px",
    color: "#fff",
    minHeight: "400px",
  },
  rightColumn: {
    flex: "1 1 500px", // grow/shrink with 500px min, wraps on small screens
    minWidth: "300px",
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  rightBox: {
    flex: 1,
    backgroundColor: "#1E88E5",
    borderRadius: 8,
    padding: "0px 16px",
    color: "#fff",
    minHeight: "192px",
  },
  iconsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(120px, 1fr))",
    gap: 16,
    padding: "16px 0",
  },
  iconCard: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 12,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    cursor: "pointer",
    transition: "transform 0.2s, box-shadow 0.2s, outline 0.2s",
    border: "none",
  },
  iconCardSelected: {
    outline: "3px solid #fff",
    outlineOffset: "4px",
    transform: "scale(1.02)",
  },
  iconImage: {
    width: 80,
    height: 80,
    objectFit: "contain",
    marginBottom: 8,
  },
  iconPrice: {
    fontSize: 14,
    fontWeight: 600,
    color: "#000000ff",
    marginTop: 4,
  },
  purchaseSection: {
    position: "fixed",
    bottom: 20,
    left: "50%",
    transform: "translateX(-50%)",
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 8,
    boxShadow: "0 4px 12px rgba(0,0,0,0.3)",
    display: "flex",
    gap: 12,
    alignItems: "center",
    zIndex: 9999,
  },
  selectedInfo: {
    fontSize: 16,
    fontWeight: 500,
    color: "#333",
  },
  popup: {
    position: "fixed",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    backgroundColor: "#fff",
    padding: 24,
    borderRadius: 8,
    boxShadow: "0 4px 20px rgba(0,0,0,0.3)",
    zIndex: 10000,
    textAlign: "center",
  },
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    zIndex: 9999,
  },
  bannersContainer: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    padding: "16px 0",
  },
  bannerCard: {
    height: 35,
    borderRadius: 8,
    marginLeft: 10,
    marginRight: 10,
    cursor: "pointer",
    transition: "transform 0.2s, outline 0.2s",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingRight: 16,
    border: "none",
  },
  bannerCardSelected: {
    outline: "3px solid #fff",
    outlineOffset: "4px",
    transform: "scale(1.02)",
  },
  bannerPrice: {
    fontSize: 14,
    fontWeight: 600,
    color: "#fff",
    backgroundColor: "rgba(0,0,0,0.3)",
    padding: "4px 12px",
    borderRadius: 4,
  },
  backdropsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(120px, 1fr))",
    gap: 16,
    padding: "16px 0",
  },
  backdropCard: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 12,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    cursor: "pointer",
    transition: "transform 0.2s, outline 0.2s",
    border: "none",
  },
  backdropCardSelected: {
    outline: "3px solid #fff",
    outlineOffset: "4px",
    transform: "scale(1.02)",
  },
  backdropContainer: {
    width: 80,
    height: 80,
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  backdropImage: {
    width: 50,
    height: 50,
    objectFit: "contain",
    position: "relative",
    zIndex: 2,
  },
  backdropPrice: {
    fontSize: 14,
    fontWeight: 600,
    color: "#000000ff",
    marginTop: 4,
  },
};

export default storeStyles;
