
export const TimeTrackingStyle = {
  container: {
    backgroundColor: '#f3f4f6',
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
  },
  layout: {
    display: 'flex',
    flex: 1,
  },
  main: {
    flex: 1,
    padding: '2rem',
    backgroundColor: '#f3f4f6', 
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  formPanel: {
    backgroundColor: '#e5e7eb', 
    padding: '2rem',
    borderRadius: '12px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.05)',
    width: '100%',
    maxWidth: 500,
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  title: {
    fontSize: 24,
    fontWeight: 700,
    marginBottom: '1rem',
    textAlign: 'center',
    color: '#1f2937',
  },
  label: {
    fontWeight: 600,
    marginBottom: '0.25rem',
    color: '#111827',
  },
  select: {
    width: '100%',
    padding: '0.5rem 0.75rem',
    borderRadius: '6px',
    border: '1px solid #d1d5db',
    fontSize: 16,
  },
  input: {
    width: '100%',
    padding: '0.5rem 0.75rem',
    borderRadius: '6px',
    border: '1px solid #d1d5db',
    fontSize: 16,
  },
  row: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '0.5rem',
  },
  switchLabel: {
    fontWeight: 600,
  },
  toggle: {
    position: 'relative',
    width: 50,
    height: 25,
    borderRadius: 25,
    cursor: 'pointer',
    transition: 'background 0.3s',
  },
  toggleCircle: {
    position: 'absolute',
    top: 3,
    width: 19,
    height: 19,
    backgroundColor: '#fff',
    borderRadius: '50%',
    transition: 'left 0.3s',
  },
  actionButtons: {
    display: 'flex',
    gap: '1rem',
    marginTop: '1.5rem',
    justifyContent: 'center',
  },
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    height: '100vh',
    backgroundColor: 'rgba(0,0,0,0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  popup: {
    backgroundColor: '#e5e7eb', 
    borderRadius: 12,
    padding: '2rem',
    textAlign: 'center',
    width: '90%',
    maxWidth: 350,
    boxShadow: '0 2px 8px rgba(0,0,0,0.05)',
  },
  popupText: {
    fontWeight: 600,
    fontSize: 18,
    marginBottom: '1rem',
    color: '#111827',
  },
  popupButtons: {
    display: 'flex',
    justifyContent: 'center',
    gap: '1rem',
  },
};

export default TimeTrackingStyle;
